DEBUG = True
MYSQL_HOST = 'localhost' # or '127.0.0.1'
MYSQL_USER = 'sunmin'
MYSQL_PASSWORD = 'Ss_123456'
MYSQL_DATABASE = 'power_loss'

SQLALCHEMY_DATABASE_URI = f'mysql+pymysql://{MYSQL_USER}:{MYSQL_PASSWORD}@{MYSQL_HOST}/{MYSQL_DATABASE}'
SQLALCHEMY_TRACK_MODIFICATIONS = False